[package]
name = "mpassgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpass = { path = "../mpass" }
regex = "1.10.3"
