//! The default word list for word-based Random Token Generators
//! A variation of this list is used when no token list is specified.

/// Get a list of words hopefully acceptable to users of all literacy levels.
/// This list consists of approximately 500 words. The list was generated by
/// taking a list of the most common English nouns, constraining length (3-6 letters),
/// and curating it to remove anything that could be considered sensitive, workplace
/// inappropriate, or difficult to spell.
/// The intent is to provide a list that, when used to generate a passphrase that will be provided
/// to a user whose language skills are minimal, will hopefully reduce spelling errors
/// and other communication problems.
/// The words are Proper Case (Initial Caps) to save on complexity during initialization.
pub fn get_simpleton_propercase_words() -> Vec<&'static str> {
    vec![
        "Time", "Way", "Year", "Work", "Day", "World", "Life", "Part", "House", "Course", "Case",
        "Place", "End", "Group", "Party", "School", "Fact", "Money", "Point", "State", "Night",
        "Area", "Water", "Thing", "Head", "Hand", "Order", "Side", "Home", "Week", "Power", "Room",
        "Market", "Lot", "Car", "Road", "Form", "Face", "Sort", "Office", "Person", "Health",
        "Name", "Book", "Level", "View", "Door", "Line", "South", "City", "Center", "Effect",
        "Staff", "Kind", "Job", "Action", "Act", "North", "Age", "Idea", "West", "Moment", "Sense",
        "Report", "Mind", "Change", "Land", "Care", "Range", "Table", "Back", "Trade", "Study",
        "Street", "Rate", "Word", "Food", "Result", "Team", "Other", "Sir", "Air", "Role",
        "Reason", "Price", "Town", "Class", "Nature", "Union", "Bank", "Member", "Value", "Need",
        "East", "Type", "Paper", "Date", "Figure", "Right", "Club", "Voice", "Stage", "King",
        "Light", "Tax", "March", "Art", "Board", "May", "Month", "Music", "Cost", "Field", "Award",
        "Issue", "Bed", "Game", "Amount", "Basis", "Series", "Top", "News", "Front", "Future",
        "Rest", "Labor", "Hair", "Bill", "Heart", "Force", "Letter", "Model", "Growth", "Fire",
        "Chance", "Sea", "Record", "Size", "Space", "Term", "Plan", "Energy", "Income", "Cup",
        "Scheme", "Design", "Choice", "Hall", "List", "Loss", "County", "Wall", "Hotel", "Sun",
        "Summer", "Set", "Color", "Floor", "Season", "Unit", "Park", "Hour", "Test", "Garden",
        "Style", "Look", "Deal", "Charge", "Help", "New", "Page", "Risk", "Advice", "Event",
        "Fish", "Oil", "Doctor", "Film", "Press", "Extent", "Window", "Shop", "Access", "Region",
        "Doubt", "Degree", "Sound", "Site", "Title", "Return", "Public", "Glass", "Answer",
        "Earth", "Leader", "River", "Eye", "Appeal", "Task", "Sale", "Whole", "Method", "Source",
        "Piece", "Lack", "Demand", "Post", "Mouth", "Radio", "Sector", "Firm", "Status", "Peace",
        "Show", "Arm", "Base", "Miss", "Safety", "Box", "Past", "Weight", "Start", "League",
        "Budget", "Share", "Cash", "Aid", "Rule", "Tea", "Truth", "Turn", "Smith", "Review",
        "Minute", "Duty", "Stone", "Dog", "Speech", "Queen", "Stock", "Effort", "Career", "Length",
        "Horse", "Plant", "Visit", "Ball", "Memory", "Bar", "Impact", "Scale", "Image", "Trust",
        "Edge", "Gas", "Gold", "Wood", "Text", "Forest", "Sister", "Chair", "Cause", "Foot",
        "Rise", "Half", "Winter", "Corner", "Step", "Damage", "Credit", "Speed", "Crime", "Hill",
        "Debate", "Supply", "Wind", "Band", "Museum", "Farm", "Pound", "Match", "Animal", "Skin",
        "Scene", "Stuff", "Play", "Island", "Claim", "Video", "Move", "Target", "Trial", "Rock",
        "Spirit", "Coffee", "Phone", "Train", "Sight", "Factor", "Battle", "Grant", "Tree",
        "Bridge", "Shape", "Wine", "Star", "Hope", "Detail", "Path", "Client", "Search", "Rain",
        "Offer", "Goal", "Dinner", "While", "Seat", "Manner", "Favor", "Pair", "Smile", "Prince",
        "Danger", "Call", "Output", "Note", "Tour", "Middle", "Track", "Card", "Sign", "Player",
        "Threat", "Notice", "Bottom", "Fund", "File", "Profit", "Route", "Second", "Cell",
        "Castle", "Lead", "Option", "Reform", "Spring", "Touch", "Estate", "Volume", "Youth",
        "Boat", "Branch", "Bus", "Waste", "Heat", "Neck", "Object", "Driver", "Code", "Crown",
        "Entry", "Bag", "Coal", "Leg", "Belief", "Total", "Major", "Aim", "Flight", "Treaty",
        "Copy", "Acid", "Lunch", "Engine", "Cross", "Key", "Vote", "Judge", "Sky", "Breath", "Row",
        "Guide", "Milk", "Cover", "Screen", "Silver", "Green", "Run", "Coast", "Valley", "Drive",
        "Metal", "Motion", "Index", "Sport", "Tape", "Flow", "Iron", "Trip", "Lane", "Pool",
        "Hole", "Flat", "Pay", "Noise", "Author", "Nation", "Sample", "Aspect", "Agent", "Ship",
        "Van", "Meal", "Motor", "Tone", "Sheet", "Beauty", "Square", "Vision", "Spot", "Brown",
        "Crowd", "Fuel", "Desk", "Sum", "Fall", "Diet", "Soil", "Reader", "Shock", "Fruit",
        "Behalf", "Deputy", "Roof", "Nose", "Steel", "Artist", "Plate", "Song", "Grass", "Ice",
        "Talk", "Link", "Ring", "Expert", "Rail", "Strike", "Map", "Lake", "Border", "Bottle",
        "Bird", "Cat", "Guy", "Dress", "Theme", "Error", "Loan", "Stress", "Wealth", "Walk",
        "Focus", "Chief", "Sleep", "Mass", "Bath", "Item", "Decade", "Beach", "Sugar", "Height",
        "Writer", "Panel", "Dream", "Pub", "Port", "Bread", "Chain", "Worker", "Empire", "Mirror",
        "Travel", "Block", "Meat", "Store", "Self", "Break", "Drama", "Skill", "Round", "Scope",
        "Gate", "Mill", "Golf", "Plane", "Gap", "Core", "Fun", "Snow", "Limit",
    ]
}
